In [12]:
import pandas as pd

df=pd.read_csv('dummy_data.csv')

df=df[df['Description of Scheme']=='Membership - IET, IEEE, CSI, ASM']
df.groupby(['year','sentiment_label'])['Record No.'].size().reset_index(name='count')

    year sentiment_label  count
0   2017         Neutral      4
1   2017        Positive     78
2   2018         Neutral      8
3   2018        Positive     87
4   2019         Neutral      5
5   2019        Positive     88
6   2020         Neutral     10
7   2020        Positive    105
8   2021         Neutral     11
9   2021        Positive     76
10  2022         Neutral      8
11  2022        Positive     83
12  2023         Neutral     14
13  2023        Positive     83
14  2024         Neutral      4
15  2024        Positive     21